services:
  github-readme-stats-render:
    container_name: github-readme-stats-render
    image: 404e/github-readme-stats-render:1.3.0
    environment:
      SERVER_HOST: 0.0.0.0 # 容器内地址
      SERVER_PORT: 80 # 容器内端口
      PROXY_TYPE: HTTP
      PROXY_HOST: 172.17.0.1 # 宿主机代理地址
      PROXY_PORT: 7890
      WAKA_TOKEN: waka_xxxx # wakatime token
      GITHUB_TOKEN: ghp_xxxx # github token
      START_CMD: "java -jar app.jar"
    volumes:
      - ./font:/app/font # 字体文件夹
      - /dev/null:/app/logs # 禁用日志
    restart: unless-stopped
    ports:
      - "80:80" # 绑定宿主机端口